# Generated by Django 4.0.5 on 2022-06-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, upload_to='posts/title_images/%Y/%m/%d/'),
        ),
    ]
