# Generated by Django 4.0.5 on 2022-06-25 18:35

import Blog.fields
import Blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_post_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=Blog.fields.WEBPField(default='posts/home-bg.webp', upload_to=Blog.models.image_folder, validators=[Blog.models.validate_image]),
        ),
    ]
