# Generated by Django 4.0.5 on 2022-06-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='Paceholder', max_length=1000),
            preserve_default=False,
        ),
    ]
